import Link from "next/link";
import Image from "next/image";
import { products } from "@/lib/products";
import { Breadcrumbs, CTASection, EnquiryLink, FAQList, ProductGrid, SectionHeading } from "@/components/site";

export function ProductPage({ product }) {
  const related = products.filter((item) => item.slug !== product.slug).slice(0, 3);
  const productSchema = {
    "@context": "https://schema.org",
    "@type": "Product",
    name: product.name,
    description: product.description,
    category: "Underwear manufacturing enquiry",
  };
  return <>
    <section className="bg-cream px-5 pb-16 pt-8 sm:px-8 sm:pb-20 lg:px-12"><div className="mx-auto max-w-[1360px]"><Breadcrumbs items={[{ label: "Products", href: "/products" }, { label: product.name }]} /><div className="grid items-center gap-10 lg:grid-cols-[0.95fr_1.05fr]"><div className="max-w-2xl py-6"><p className="mb-5 text-[10px] font-semibold uppercase tracking-[0.19em] text-olive-700">Custom product development · B2B enquiries</p><h1 className="font-display text-5xl leading-[1.02] tracking-[-0.04em] text-ink sm:text-7xl">{product.title}</h1><p className="mt-6 max-w-xl text-base leading-7 text-ink/65">{product.description}</p><div className="mt-8 flex flex-wrap gap-3"><EnquiryLink product={product.name} /><Link href="/private-label" className="inline-flex min-h-12 items-center border border-ink/25 px-6 text-xs font-semibold uppercase tracking-[0.12em] text-ink hover:border-ink">Private label details</Link></div></div><div className="relative aspect-[4/3] overflow-hidden bg-stone-200"><Image src={product.image} alt={product.imageAlt} fill priority sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /><span className="absolute bottom-4 left-4 bg-cream/95 px-3 py-2 text-[9px] uppercase tracking-[0.14em]">Illustrative image · not a company product sample</span></div></div></div></section>

    <section className="bg-white px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-[1360px] gap-12 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading eyebrow={`${product.name} manufacturing`} title={`A product brief for ${product.name.toLowerCase()}.`} description={product.description} /><div className="border-t border-ink/15"><div className="border-b border-ink/15 py-6"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-olive-700">Product overview</p><p className="mt-3 max-w-2xl text-sm leading-7 text-ink/65">Share your intended customer, target fit, reference products and technical requirements. A clear brief helps establish the development conversation and what needs to be confirmed before sampling or bulk production planning.</p></div><div className="border-b border-ink/15 py-6"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-olive-700">Development & manufacturing</p><p className="mt-3 max-w-2xl text-sm leading-7 text-ink/65">The project may involve pattern and specification review, material selection, sample development, approval, production planning, finishing and packing. Exact steps and feasibility depend on your product and are confirmed with the team.</p></div><div className="py-6"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-olive-700">Related services</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-3 text-sm">{[{ label: "Private label manufacturing", href: "/private-label" }, { label: "Manufacturing process", href: "/manufacturing" }, { label: "Custom underwear", href: "/custom-underwear" }, { label: "Contact the team", href: "/contact" }].map((item) => <Link key={item.href} href={item.href} className="text-ink underline decoration-ink/25 underline-offset-4 hover:text-olive-800">{item.label} ↗</Link>)}</div></div></div></div></section>

    <section className="bg-lime-300 px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-[1360px] gap-10 md:grid-cols-[0.8fr_1.2fr]"><SectionHeading eyebrow="Customize the brief" title="Your specification sets the direction." description="These are discussion areas, not a promise of availability. The team confirms product-specific options after reviewing the brief." /><div className="grid grid-cols-2 border-t border-ink/20 sm:grid-cols-3">{product.customization.map((item, index) => <div key={item} className="flex min-h-24 flex-col justify-between border-b border-ink/20 p-4 sm:min-h-28 sm:p-5"><span className="text-[10px] text-olive-800">0{index + 1}</span><span className="text-sm text-ink">{item}</span></div>)}</div></div></section>

    <section className="bg-olive-950 px-5 py-16 text-cream sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-[1360px] gap-10 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading eyebrow="Branding & finishing" title="Private label belongs in the plan." description="Labels, care details, waistband branding and packaging may be considered as part of your product specification. Confirm the exact options for this style before proceeding." light /><div className="grid grid-cols-2 border-t border-cream/20 sm:grid-cols-4">{["Main labels", "Care labels", "Waistband", "Packaging"].map((item, index) => <div key={item} className="flex min-h-28 flex-col justify-between border-b border-cream/20 p-4 sm:border-r sm:p-5"><span className="font-display text-xl text-lime-200">0{index + 1}</span><span className="text-sm text-cream/80">{item}</span></div>)}</div></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-[1360px] gap-10 lg:grid-cols-[0.7fr_1.3fr]"><SectionHeading eyebrow={`${product.name} FAQ`} title="Project-specific answers." description="Requirements vary by style and specification. Ask directly about your product." /><FAQList items={product.faq} /></div></section>

    <section className="bg-white px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-[1360px]"><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><SectionHeading eyebrow="Explore related styles" title="More underwear categories." /><Link href="/products" className="text-xs font-semibold uppercase tracking-[0.12em] text-olive-800 underline underline-offset-4">View all products ↗</Link></div><ProductGrid items={related} /></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema).replace(/</g, "\\u003c") }} />
    <CTASection title={`Discuss your ${product.name.toLowerCase()} project.`} description="Share a reference, tech pack or early idea and include your estimated order quantity." />
  </>;
}