import Link from "next/link";
import Image from "next/image";
import { Breadcrumbs, CTASection, EnquiryLink, SectionHeading } from "@/components/site";

function AboutHero({ page }) {
  return <section className="bg-cream px-5 pb-12 pt-8 sm:px-8 sm:pb-16 lg:px-12"><div className="mx-auto max-w-[1360px]"><Breadcrumbs items={[{ label: page.nav }]} /><div className="grid gap-10 pb-10 lg:grid-cols-[1.15fr_0.85fr] lg:items-end"><div><p className="mb-5 text-[10px] font-semibold uppercase tracking-[0.2em] text-olive-700">{page.eyebrow}</p><h1 className="max-w-4xl font-display text-6xl leading-[0.96] tracking-[-0.045em] text-ink sm:text-8xl">A better brief begins with <span className="text-[#bd503c]">a conversation.</span></h1></div><div className="max-w-md pb-2"><p className="text-base leading-7 text-ink/70">{page.description}</p><EnquiryLink className="mt-6" /></div></div><figure className="relative h-[330px] overflow-hidden bg-stone-200 sm:h-[480px] lg:h-[560px]"><Image src={page.image} alt={page.imageAlt} fill priority sizes="100vw" className="object-cover object-center" /><figcaption className="absolute bottom-4 left-4 bg-cream/95 px-4 py-3 text-[10px] uppercase tracking-[0.12em] text-ink/75">Illustrative garment-sector image · not the represented company&apos;s facility</figcaption><span className="absolute right-4 top-4 bg-[#e36d50] px-4 py-3 text-xs font-semibold uppercase tracking-[0.1em] text-ink">{page.nav}</span></figure></div></section>;
}

function ManufacturingHero({ page }) {
  return <section className="bg-ink px-5 pb-14 pt-8 text-cream sm:px-8 sm:pb-20 lg:px-12"><div className="mx-auto max-w-[1360px]"><Breadcrumbs items={[{ label: page.nav }]} /><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div className="pb-2"><p className="mb-5 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#f1c3ae]">{page.eyebrow}</p><h1 className="max-w-3xl font-display text-5xl leading-[1] tracking-[-0.04em] text-cream sm:text-7xl">The work behind the <span className="text-[#e36d50]">wear.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-cream/70">{page.description}</p><EnquiryLink className="mt-7" variant="accent" /></div><figure className="relative aspect-[5/4] overflow-hidden bg-[#353a36]"><Image src={page.image} alt={page.imageAlt} fill priority sizes="(min-width: 1024px) 55vw, 100vw" className="object-cover opacity-85" /><figcaption className="absolute bottom-4 left-4 bg-ink/85 px-3 py-2 text-[9px] uppercase tracking-[0.14em] text-cream/80">Production concept imagery · verify and replace</figcaption></figure></div><div className="mt-10 grid border-l border-t border-white/20 sm:grid-cols-4">{["Product brief", "Development", "Sample review", "Production plan"].map((step, index) => <div key={step} className="flex min-h-20 items-center gap-3 border-b border-r border-white/20 px-4 py-4"><span className="font-display text-2xl text-[#f1c3ae]">0{index + 1}</span><span className="text-xs uppercase tracking-[0.07em] text-cream/75">{step}</span></div>)}</div></div></section>;
}

function PrivateLabelHero({ page }) {
  return <section className="bg-[#e36d50] px-5 pb-14 pt-8 sm:px-8 sm:pb-20 lg:px-12"><div className="mx-auto max-w-[1360px]"><Breadcrumbs items={[{ label: page.nav }]} /><div className="grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><div className="py-4"><p className="mb-5 text-[10px] font-semibold uppercase tracking-[0.2em] text-ink/70">{page.eyebrow}</p><h1 className="max-w-3xl font-display text-5xl leading-[0.98] tracking-[-0.045em] text-ink sm:text-7xl">Your label. Your details. <span className="text-cream">Your point of view.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-ink/75">{page.description}</p><EnquiryLink className="mt-7" /></div><figure className="relative min-h-[360px] overflow-hidden bg-cream sm:min-h-[500px]"><Image src={page.image} alt={page.imageAlt} fill priority sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover" /><figcaption className="absolute left-4 top-4 bg-cream/95 px-3 py-2 text-[9px] uppercase tracking-[0.13em] text-ink/75">Illustrative garment-sector image · see image credits</figcaption><div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-3 bg-cream/95 p-5 sm:p-7"><div><p className="text-[9px] uppercase tracking-[0.16em] text-ink/55">Branding, considered</p><p className="mt-2 font-display text-3xl text-ink">Details that make it yours.</p></div><span aria-hidden="true" className="grid size-12 shrink-0 place-items-center rounded-full bg-ink text-xl text-cream">↗</span></div></figure></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 border-t border-ink/20 pt-5 text-[10px] font-semibold uppercase tracking-[0.13em] text-ink/75">{["Main labels", "Care details", "Waistband", "Packaging"].map((label) => <span key={label}>{label}</span>)}</div></div></section>;
}

function CustomHero({ page }) {
  return <section className="bg-cream px-5 pb-14 pt-8 sm:px-8 sm:pb-20 lg:px-12"><div className="mx-auto max-w-[1360px]"><Breadcrumbs items={[{ label: page.nav }]} /><div className="grid gap-10 lg:grid-cols-[1fr_1fr] lg:items-center"><div className="relative order-2 aspect-[4/5] max-h-[660px] overflow-hidden bg-stone-200 lg:order-1"><Image src={page.image} alt={page.imageAlt} fill priority sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /><span className="absolute bottom-4 left-4 bg-cream/95 px-3 py-2 text-[9px] uppercase tracking-[0.13em]">Historical garment reference · not a current sample</span></div><div className="order-1 py-5 lg:order-2 lg:pl-8"><p className="mb-5 text-[10px] font-semibold uppercase tracking-[0.2em] text-olive-700">{page.eyebrow}</p><h1 className="font-display text-5xl leading-[0.98] tracking-[-0.045em] text-ink sm:text-7xl">An idea becomes a garment one decision at a time.</h1><p className="mt-6 max-w-xl text-base leading-7 text-ink/65">{page.description}</p><div className="mt-8 border-l-2 border-[#e36d50] pl-5"><p className="font-display text-2xl text-ink">Fit. Fabric. Finish.</p><p className="mt-2 max-w-sm text-sm leading-6 text-ink/60">Set the direction for each detail with a sketch, a sample or a technical pack.</p></div><EnquiryLink className="mt-8" variant="accent" /></div></div></div></section>;
}

function SectionBlock({ section, index, artDirection }) {
  if (artDirection === "process") {
    return <section key={section.title} className="border-t border-ink/15 bg-cream px-5 py-12 sm:px-8 sm:py-16 lg:px-12"><div className="mx-auto grid max-w-[1360px] gap-6 md:grid-cols-[100px_0.8fr_1.2fr]"><span className="font-display text-5xl text-[#bd503c]">0{index + 1}</span><h2 className="max-w-md font-display text-3xl leading-tight tracking-[-0.025em] text-ink sm:text-4xl">{section.title}</h2><div><p className="max-w-2xl text-sm leading-7 text-ink/65">{section.text}</p>{section.link && <Link href={section.link.href} className="mt-5 inline-flex text-xs font-semibold uppercase tracking-[0.12em] text-olive-800 underline underline-offset-4">{section.link.label} ↗</Link>}</div></div></section>;
  }
  if (artDirection === "label") {
    return <section key={section.title} className={`px-5 py-14 sm:px-8 sm:py-20 lg:px-12 ${index % 2 === 0 ? "bg-white" : "bg-cream"}`}><div className="mx-auto grid max-w-[1360px] gap-8 lg:grid-cols-[0.55fr_1.45fr]"><div className="flex items-start gap-4"><span className="font-display text-4xl text-[#bd503c]">0{index + 1}</span><p className="pt-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-ink/50">Private label / detail</p></div><div className="grid gap-5 sm:grid-cols-[0.8fr_1.2fr]"><h2 className="max-w-md font-display text-3xl leading-tight tracking-[-0.025em] text-ink sm:text-4xl">{section.title}</h2><div><p className="text-sm leading-7 text-ink/65">{section.text}</p>{section.link && <Link href={section.link.href} className="mt-5 inline-flex text-xs font-semibold uppercase tracking-[0.12em] text-olive-800 underline underline-offset-4">{section.link.label} ↗</Link>}</div></div></div></section>;
  }
  return <section key={section.title} className={`${index % 2 === 0 ? "bg-white" : "bg-cream"} px-5 py-14 sm:px-8 sm:py-20 lg:px-12`}><div className={`mx-auto grid max-w-[1360px] gap-8 lg:gap-14 ${index % 2 ? "md:grid-cols-[1.15fr_0.85fr]" : "md:grid-cols-[0.85fr_1.15fr]"}`}><div className={index % 2 ? "md:order-2" : ""}><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-olive-700">{pageLabel(artDirection)} / 0{index + 1}</p><h2 className="max-w-xl font-display text-3xl leading-tight tracking-[-0.025em] text-ink sm:text-4xl">{section.title}</h2></div><div className={index % 2 ? "md:order-1" : ""}><p className="max-w-2xl text-base leading-7 text-ink/65">{section.text}</p>{section.items && <ul className="mt-6 grid gap-x-8 border-t border-ink/15 sm:grid-cols-2">{section.items.map((item, itemIndex) => <li key={item} className="flex gap-4 border-b border-ink/15 py-4 text-sm text-ink/75"><span className="text-[10px] text-[#bd503c]">0{itemIndex + 1}</span>{item}</li>)}</ul>}{section.link && <Link href={section.link.href} className="mt-6 inline-flex text-xs font-semibold uppercase tracking-[0.12em] text-olive-800 underline underline-offset-4">{section.link.label} ↗</Link>}</div></div></section>;
}

function pageLabel(artDirection) {
  return artDirection === "studio" ? "Our approach" : "Product development";
}

export function ServicePage({ page }) {
  const Hero = page.artDirection === "studio" ? AboutHero : page.artDirection === "process" ? ManufacturingHero : page.artDirection === "label" ? PrivateLabelHero : CustomHero;
  return <>
    <Hero page={page} />
    {page.sections.map((section, index) => <SectionBlock key={section.title} section={section} index={index} artDirection={page.artDirection} />)}
    {page.artDirection === "studio" && <section className="relative h-[360px] overflow-hidden bg-stone-200 sm:h-[500px]"><Image src="/images/garment-sewing-floor.jpg" alt="Illustrative garment sewing floor, not the represented company's facility" fill loading="lazy" sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-ink/25" /><p className="absolute bottom-6 left-5 max-w-xl font-display text-4xl text-white sm:left-12 sm:text-6xl">Start with the detail that matters most.</p></section>}
    {page.artDirection === "process" && <section className="bg-[#e36d50] px-5 py-14 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-[1360px] gap-8 lg:grid-cols-[0.7fr_1.3fr]"><SectionHeading eyebrow="Production workflow" title="A sequence, not a promise." description="The specific operation, timing and production capabilities are confirmed against the product brief." /><div className="grid grid-cols-2 border-l border-t border-ink/25 sm:grid-cols-4">{(page.process || []).map((step, index) => <div key={step} className="min-h-32 border-b border-r border-ink/25 p-4 sm:p-5"><span className="font-display text-3xl text-ink/55">0{index + 1}</span><p className="mt-4 text-xs font-semibold uppercase tracking-[0.08em] text-ink">{step}</p></div>)}</div></div></section>}
    {page.artDirection !== "process" && <section className="bg-ink px-5 py-14 text-cream sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-[1360px] items-end gap-8 md:grid-cols-[1fr_auto]"><div><p className="mb-4 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f1c3ae]">{page.processEyebrow || "A considered process"}</p><h2 className="max-w-2xl font-display text-4xl leading-tight tracking-[-0.03em] sm:text-5xl">{page.processTitle || "Project details are confirmed at each step."}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-cream/65">{page.processDescription || "Share your requirements early. The team can review the brief, identify open questions and confirm which steps apply."}</p></div><EnquiryLink variant="accent" /></div></section>}
    <CTASection title={page.ctaTitle || "Start with a clear project brief."} description={page.ctaDescription || "Send the product type, reference and questions you would like to discuss."} />
  </>;
}