const sharedCustomization = [
  "Fabric and material direction",
  "Fit and size range",
  "Color and finish",
  "Waistband and stitching details",
  "Labels, branding and packaging",
];

export const products = [
  {
    slug: "boxers",
    name: "Boxers",
    title: "Custom Boxers Manufacturer",
    shortDescription: "A considered foundation for branded boxer collections.",
    description: "Explore a boxer brief or woven boxer project shaped around your fit, fabric and brand requirements. Product details and production suitability are confirmed for each enquiry.",
    image: "/images/vintage-underpants-reference.jpg",
    imageAlt: "Historical boxer-style underpants from a museum collection, not a current product or company sample",
    customization: sharedCustomization,
    faq: [
      { question: "Can boxers be developed to our specification?", answer: "Share your reference, tech pack or initial brief. The team can review the requested fit, materials and details and confirm what is possible for your project." },
      { question: "Can boxers carry our own branding?", answer: "Private-label details such as labels, waistbands and packaging can be discussed as part of your enquiry. Available options are confirmed project by project." },
    ],
  },
  {
    slug: "briefs",
    name: "Briefs",
    title: "Custom Briefs Manufacturer",
    shortDescription: "A clean, adaptable brief silhouette for your range.",
    description: "Discuss a custom briefs project with details built around the intended fit, fabric, color and branding. Final specifications are agreed with your team before sampling or production planning.",
    image: "/images/garment-sewing-floor.jpg",
    imageAlt: "Illustrative garment sewing floor, not a briefs product image or the represented company's facility",
    customization: sharedCustomization,
    faq: [
      { question: "Can I specify the fit and rise of briefs?", answer: "Include your fit direction, reference garment or tech pack in the enquiry so the requested details can be reviewed." },
      { question: "Can briefs be made in custom colors?", answer: "Color requirements can be included in your brief. Material and color feasibility is confirmed during project review." },
    ],
  },
  {
    slug: "boxer-briefs",
    name: "Boxer briefs",
    title: "Custom Boxer Brief Manufacturer",
    shortDescription: "A versatile longer-leg silhouette for everyday ranges.",
    description: "Build a boxer brief concept around your preferred leg length, fit, fabric and branded finishing. Share your technical requirements for a project-specific review.",
    image: "/images/garment-production-floor.jpg",
    imageAlt: "Illustrative garment production floor, not a boxer brief product image or the represented company's facility",
    customization: sharedCustomization,
    faq: [
      { question: "Can the leg length and fit be customized?", answer: "Specify your preferred measurements or provide a tech pack. Requested construction details can then be reviewed for feasibility." },
      { question: "Do you support private-label boxer briefs?", answer: "Branding and label requirements can be included with your product brief. Confirmed options depend on the project specification." },
    ],
  },
  {
    slug: "trunks",
    name: "Trunks",
    title: "Custom Trunks Manufacturer",
    shortDescription: "A compact silhouette to develop for your own label.",
    description: "Discuss custom trunks with a brief covering fit, fabric, waistband, color and finishing. Product capabilities are confirmed against each brand's requirements.",
    image: "/images/garment-sewing-workstation.jpg",
    imageAlt: "Illustrative garment sewing workstation, not a trunks product image or the represented company's production line",
    customization: sharedCustomization,
    faq: [
      { question: "Can trunks use a branded waistband?", answer: "A branded waistband can be discussed in your enquiry. Share artwork or a reference so requirements can be assessed." },
      { question: "Can I request a custom trunk sample?", answer: "Ask about sample development when you enquire. Timing, process and availability are confirmed for the project." },
    ],
  },
  {
    slug: "sports-underwear",
    name: "Sports underwear",
    title: "Custom Sports Underwear Manufacturer",
    shortDescription: "Performance-minded concepts specified for your audience.",
    description: "Share the intended use, fit, material preferences and performance requirements for a sports underwear concept. Material and construction suitability must be confirmed before any claims are made.",
    image: "/images/garment-production-floor.jpg",
    imageAlt: "Illustrative garment production floor, not a sports underwear product image or the represented company's facility",
    customization: sharedCustomization,
    faq: [
      { question: "Can sports underwear be developed around a specific activity?", answer: "Describe the intended activity and wearer requirements in your brief. The team can review the specification and confirm suitable options." },
      { question: "Can you confirm technical fabric performance?", answer: "No performance claim is made by this site. Any material properties must be specified and verified for the selected fabric and finished product." },
    ],
  },
  {
    slug: "seamless-underwear",
    name: "Seamless underwear",
    title: "Custom Seamless Underwear Manufacturer",
    shortDescription: "A specialist construction enquiry for your next range.",
    description: "Seamless construction can involve specific machinery and development requirements. Share your concept to confirm whether the requested product can be supported.",
    image: "/images/garment-sewing-floor.jpg",
    imageAlt: "Illustrative garment sewing floor, not a seamless underwear product image or the represented company's facility",
    customization: sharedCustomization,
    faq: [
      { question: "Is seamless production available for every project?", answer: "Availability is not assumed. Share your reference and requirements so the team can confirm whether the construction is supported." },
      { question: "Can seamless underwear be branded?", answer: "Branding options depend on product construction. Include your label and packaging requirements in the enquiry for review." },
    ],
  },
  {
    slug: "thermal-underwear",
    name: "Thermal underwear",
    title: "Custom Thermal Underwear Manufacturer",
    shortDescription: "Layering essentials developed around a clear product brief.",
    description: "Outline the intended climate, layering use, fit and material preferences. Fabric suitability and product construction should be agreed and verified for your project.",
    image: "/images/garment-sewing-workstation.jpg",
    imageAlt: "Illustrative garment sewing workstation, not a thermal underwear product image or the represented company's production line",
    customization: sharedCustomization,
    faq: [
      { question: "Can I specify the fabric weight for thermal underwear?", answer: "Include your preferred fabric weight or reference in the project brief. Feasibility can be confirmed during material review." },
      { question: "Can you guarantee a thermal performance rating?", answer: "No rating or performance guarantee is stated here. Any required test standard must be agreed and verified for the final material and garment." },
    ],
  },
  {
    slug: "custom-underwear",
    name: "Custom underwear",
    title: "Custom Underwear Manufacturer",
    shortDescription: "Start with an idea, sketch, reference or complete tech pack.",
    description: "A custom underwear enquiry can start from an early concept or a detailed specification. Share the product direction and the team can discuss development steps and feasibility.",
    image: "/images/garment-sewing-floor.jpg",
    imageAlt: "Illustrative garment sewing floor, not a custom underwear sample or the represented company's facility",
    customization: sharedCustomization,
    faq: [
      { question: "Can you help develop underwear from an idea?", answer: "Describe your concept, intended customer and references. The team can review the information and confirm possible next steps." },
      { question: "Do I need a tech pack to enquire?", answer: "A tech pack is helpful but not required to start a conversation. A sketch, reference or written brief can also explain your idea." },
    ],
  },
];

export const getProduct = (slug) => products.find((product) => product.slug === slug);
export const productHref = (slug) => `/products/${slug}`;