export const servicePages = {
  about: {
    artDirection: "studio",
    nav: "About", eyebrow: "About the company", title: "A partner for your next underwear brief.",
    description: "A B2B starting point for brands exploring custom underwear product development, private-label details and production planning. The project conversation begins with your requirements.",
    image: "/images/garment-production-floor.jpg",
    imageAlt: "Illustrative garment-sector production floor, not the represented company's facility",
    sections: [
      { title: "An approach led by your product", text: "Every brand brief is different. Begin with the silhouette, wearer, market and references you have in mind; open questions can be identified before decisions are made." },
      { title: "Development before production", text: "Product direction, fit, materials and construction need to align. A development conversation helps establish specifications and what should be reviewed in a sample." },
      { title: "Manufacturing details matter", text: "Cut, stitching, finishing and packing requirements are considered in relation to the product. Any process or capability is confirmed for the requested style." },
      { title: "Branding and packaging", text: "Private-label details may include main and care labels, waistband branding and packaging. Supply your requirements or artwork for a project-specific review.", link: { label: "Explore private label manufacturing", href: "/private-label" } },
    ],
    process: ["Share the product brief", "Review materials and fit", "Discuss sample development", "Confirm production details"],
    ctaTitle: "Tell us what you want to build.",
  },
  manufacturing: {
    artDirection: "process",
    nav: "Manufacturing", eyebrow: "Custom underwear manufacturing", title: "From product development to production planning.",
    description: "Explore the stages involved in an underwear manufacturing project. The route depends on the product, technical requirements and details agreed with your team.",
    image: "/images/garment-sewing-workstation.jpg",
    imageAlt: "Illustrative garment sewing workstation, not the represented company's production line",
    sections: [
      { title: "Product development & pattern direction", text: "Bring a tech pack, reference or concept. Fit intent, measurements and construction notes can be reviewed to clarify the development brief." },
      { title: "Fabric and material selection", text: "Material preferences, hand feel, weight and intended use can be included in your brief. Availability and suitability must be confirmed for the selected product." },
      { title: "Cutting, sewing & finishing", text: "Construction requirements should be agreed for each style. Discuss seams, waistband, finishing and inspection expectations as part of production planning." },
      { title: "Quality review, branding & packaging", text: "Define the inspection points, labels, branding and packing details your team expects. Any standards or certifications must be supplied and verified separately." },
    ],
    process: ["Requirements & tech pack", "Pattern and materials", "Sample review", "Production & finishing"],
    ctaTitle: "Discuss your production requirements.",
    ctaDescription: "Share the style, specification and estimated order quantity. Project details are confirmed with the manufacturing team.",
  },
  "private-label": {
    artDirection: "label",
    nav: "Private label", eyebrow: "Private label underwear manufacturer", title: "A private-label product, built around your identity.",
    description: "Discuss custom underwear production with brand details considered from the start: labels, care information, waistband, colors and packaging, subject to project-specific confirmation.",
    image: "/images/garment-sewing-floor.jpg",
    imageAlt: "Illustrative garment sewing floor, not the represented company's facility",
    sections: [
      { title: "What private label means for your project", text: "Your product is developed for your brand brief, with requested identity details discussed as part of the specification. Exact available options depend on the product and are confirmed before commitment." },
      { title: "Product development & samples", text: "Share a tech pack, sketch or reference. The team can review fit, product details and whether sample development is an appropriate next step." },
      { title: "Labels, waistbands & identity", text: "Provide your main label, care instructions, logo artwork and waistband preferences. Artwork placement, construction and feasibility are agreed for the selected product." },
      { title: "Packaging and production", text: "Include packaging format, labeling and any packing instructions in your brief. Production scope, quantities and timing are confirmed directly; no MOQ or lead time is assumed here." },
    ],
    process: ["Share brand requirements", "Review product specification", "Discuss sample and branding", "Confirm production scope"],
    ctaTitle: "Start your private-label project.",
  },
  "custom-underwear": {
    artDirection: "custom",
    nav: "Custom underwear", eyebrow: "Custom underwear manufacturer", title: "Start with a sketch. Finish with a specification.",
    description: "Bring a new underwear concept or a defined tech pack. Discuss fit, fabric, color, waistband, construction, labels and packaging for your product.",
    image: "/images/vintage-underpants-reference.jpg",
    imageAlt: "Historical boxer-style underpants held by Auckland War Memorial Museum, shown as a garment construction reference",
    sections: [
      { title: "Custom designs and fit", text: "Describe your silhouette, intended customer and fit direction. Measurements, references and construction notes help frame the product brief." },
      { title: "Fabric, color and waistband", text: "Share material preferences, color direction and waistband requirements. Options depend on availability and feasibility for the requested style." },
      { title: "Labels, branding and packaging", text: "Include your logo, label text, packaging format and any artwork. The team can review the requested finishing for the product under consideration." },
      { title: "Sample development and bulk production", text: "Sample and production discussions follow review of your requirements. Quantity, timelines and available steps are confirmed for each project rather than assumed on this page." },
    ],
    process: ["Idea or tech pack", "Product specification", "Sample discussion", "Bulk production enquiry"],
    ctaTitle: "Have a custom underwear idea?",
  },
};

export const serviceMetadata = {
  about: { title: "About | Custom Underwear Manufacturing", description: "Learn about the approach to custom underwear product development, private label details and B2B manufacturing enquiries." },
  manufacturing: { title: "Underwear Manufacturing & Production", description: "Explore product development, materials, construction, finishing and production planning for custom underwear projects." },
  "private-label": { title: "Private Label Underwear Manufacturer", description: "Discuss private-label underwear development, custom branding, labels, waistbands and packaging for your brand." },
  "custom-underwear": { title: "Custom Underwear Manufacturer", description: "Discuss custom underwear design, fabric, fit, waistband, branding, sample development and production requirements." },
};